import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class SignatureDataSummary {
  @ApiProperty({
    description: 'HMAC-SHA signature generated by Cloudinary SDK',
  })
  signature!: string;

  @ApiProperty({ example: 1711928301 })
  timestamp!: number;

  @ApiProperty({ description: 'Cloudinary API Key' })
  apiKey!: string;

  @ApiProperty({ example: 'videos/channel_123' })
  folder!: string;

  @ApiPropertyOptional({ example: 'sp_full_hd/m3u8' })
  eager?: string;

  @ApiPropertyOptional({
    description: 'Webhook URL Cloudinary pings on transcode completion',
  })
  eagerNotificationUrl?: string;

  @ApiProperty({ example: true })
  eagerAsync!: boolean;

  @ApiProperty({
    example: 'https://api.cloudinary.com/v1_1/******/video/upload',
  })
  uploadUrl!: string;
}

export class CreateVideoResponseDto {
  @ApiProperty({ example: 'vid_9876543211' })
  videoId!: string;

  @ApiProperty({ type: () => SignatureDataSummary })
  signatureData!: SignatureDataSummary;
}

export class VideoCreatedResponseDto {
  @ApiProperty({ enum: [true] })
  success!: true;

  @ApiProperty({ type: () => CreateVideoResponseDto })
  data!: CreateVideoResponseDto;

  @ApiPropertyOptional({ type: Object, nullable: true })
  meta?: Record<string, any>;
}
