import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class SignatureVideoDataSummary {
  @ApiProperty({
    description: 'HMAC-SHA signature generated by Cloudinary SDK',
  })
  signature!: string;

  @ApiProperty({ example: 1711928301 })
  timestamp!: number;

  @ApiProperty({ description: 'Cloudinary API Key' })
  apiKey!: string;

  @ApiProperty({ example: 'videos/channel_123' })
  folder!: string;

  @ApiPropertyOptional({ example: 'sp_full_hd/m3u8' })
  eager?: string;

  @ApiPropertyOptional({
    description: 'Webhook URL Cloudinary pings on transcode completion',
  })
  eager_notification_url?: string;

  @ApiProperty({ example: true })
  eager_async!: boolean;

  @ApiProperty({
    example: 'https://api.cloudinary.com/v1_1/******/video/upload',
  })
  uploadUrl!: string;

  @ApiProperty({ example: 'vid_987654321' })
  public_id!: string;
}

export class SignatureThumbnailDataSummary {
  @ApiProperty({
    description: 'HMAC-SHA signature generated by Cloudinary SDK',
  })
  signature!: string;

  @ApiProperty({ example: 1711928301 })
  timestamp!: number;

  @ApiProperty({ description: 'Cloudinary API Key' })
  apiKey!: string;

  @ApiProperty({ example: 'thumbnails/channel_123' })
  folder!: string;

  @ApiProperty({
    example: 'https://api.cloudinary.com/v1_1/******/image/upload',
  })
  uploadUrl!: string;

  @ApiProperty({ example: 'vid_987654321' })
  public_id!: string;

  @ApiProperty({ example: 'c_fill,w_1280,h_720,q_auto,f_auto' })
  transformation!: string;
}

export class CreateVideoResponseDto {
  @ApiProperty({ example: 'vid_987654321' })
  videoId!: string;

  @ApiProperty({ type: () => SignatureVideoDataSummary })
  signatureVideoData!: SignatureVideoDataSummary;

  @ApiProperty({ type: () => SignatureThumbnailDataSummary })
  signatureThumbnailData!: SignatureThumbnailDataSummary;
}

export class VideoCreatedResponseDto {
  @ApiProperty({ enum: [true] })
  success!: true;

  @ApiProperty({ type: () => CreateVideoResponseDto })
  data!: CreateVideoResponseDto;

  @ApiPropertyOptional({ type: Object, nullable: true })
  meta?: Record<string, any>;
}
